"""initial schema

Revision ID: 19bc5d755445
Revises: 
Create Date: 2026-07-08 17:05:16.994598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bc5d755445'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadet_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('platoon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadet_accounts_personal_number'), 'cadet_accounts', ['personal_number'], unique=True)
    op.create_table('job_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type_a', sa.String(), nullable=False),
    sa.Column('job_type_b', sa.String(), nullable=False),
    sa.Column('can_overlap', sa.Boolean(), nullable=False),
    sa.Column('can_be_consecutive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type_a', 'job_type_b')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=True)
    op.create_table('manager_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_users_username'), 'manager_users', ['username'], unique=True)
    op.create_table('schedule_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('t_rest', sa.Float(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('excel_path', sa.String(), nullable=True),
    sa.Column('summary_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_constraint_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_constraint_slots_team'), 'team_constraint_slots', ['team'], unique=False)
    op.create_table('cadet_forbidden_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadet_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadet_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadet_id', 'job_name')
    )
    op.create_table('cadet_unavailable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadet_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadet_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'start', 'end')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_definitions')
    op.drop_table('cadet_unavailable_slots')
    op.drop_table('cadet_forbidden_jobs')
    op.drop_index(op.f('ix_team_constraint_slots_team'), table_name='team_constraint_slots')
    op.drop_table('team_constraint_slots')
    op.drop_table('schedule_runs')
    op.drop_index(op.f('ix_manager_users_username'), table_name='manager_users')
    op.drop_table('manager_users')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('job_constraints')
    op.drop_index(op.f('ix_cadet_accounts_personal_number'), table_name='cadet_accounts')
    op.drop_table('cadet_accounts')
    # ### end Alembic commands ###
